const drawerItems = [
  {
    id: 0,
    name: 'Home',
    icon: 'home',
    path: '/',
    materialIcon: true,
  },
  {
    id: 1,
    name: 'Contests',
    icon: 'code',
    path: '/contests',
    materialIcon: true,
  },
  {
    id: 11,
    name: 'Turing Cup',
    icon: 'emoji_events',
    path: '/turingcup',
    materialIcon: true,
    new: true,
    target: '_blank',
  },
  {
    id: 2,
    name: 'Ratings',
    icon: 'star',
    path: '/ratings',
    materialIcon: true,
  },
  {
    id: 3,
    name: 'Code',
    icon: 'data_object',
    path: '/code',
    materialIcon: true,
  },
  {
    id: 4,
    name: 'Blogs',
    icon: 'library_books',
    path: '/blogs',
    materialIcon: true,
  },
  {
    id: 5,
    name: 'Problem Set',
    icon: 'question_answer',
    path: '/problem-set',
    materialIcon: true,
  },
  {
    id: 6,
    name: 'Playlists',
    icon: 'playlist_play',
    path: '/playlists',
    materialIcon: true,
  },
  // {
  //   id: 7,
  //   name: 'Goodies',
  //   icon: 'card_giftcard',
  //   path: '/goodies',
  //   materialIcon: true,
  // },
  {
    id: 8,
    name: 'Learn',
    icon: 'school',
    path: '/learn',
    materialIcon: true,
  },
  {
    id: 9,
    name: 'Labs',
    icon: 'insights',
    path: '/labs',
    materialIcon: true,
  },
  {
    id: 10,
    name: 'API',
    icon: 'api',
    path: '/api',
    materialIcon: true,
  },
];

export default drawerItems;
