const blogs = [
  {
    id: 1,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 2,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 3,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 4,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 5,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 6,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 7,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },

  {
    id: 8,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
  {
    id: 9,
    name: 'Single Round Match #03',
    tags: ['SRM', 'SRM03', 'contest'],
    author: 'Swapnil Satish Shinde',
    date: 'Jan 4, 2019',
    timeToRead: '2 min read',
    updated: '11 hours ago',
  },
];

export default blogs;
