const developers = [
  {
    id: 1,
    name: 'Omkar Prabhu (Founder)',
    imageUrl: 'https://avatars2.githubusercontent.com/u/31627958?s=460&v=4',
    githubUrl: 'https://github.com/prabhuomkar',
    linkdinUrl: 'https://linkedin.com/in/prabhu-omkar',
    twitterUrl: 'https://twitter.com/@op_prabhuomkar',
    facebookUrl: 'https://fb.com/op1111',
    instagramUrl: 'https://instagram.com/prabhu.omkar',
  },
  {
    id: 2,
    name: 'Siddharth Poduval',
    imageUrl: 'https://avatars1.githubusercontent.com/u/23222821?s=460&v=4',
    githubUrl: 'https://github.com/sudocoder98',
    linkdinUrl: 'https://www.linkedin.com/in/siddharth-poduval',
    twitterUrl: '',
    facebookUrl: 'https://fb.com/sid.poduval',
    instagramUrl: 'https://www.instagram.com/sid12598',
  },
  
  {
    id: 3,
    name: 'Mandar Kotnis',
    imageUrl: 'https://avatars2.githubusercontent.com/u/27295746?s=460&v=4',
    githubUrl: 'https://github.com/Mandar-Kotnis',
    linkdinUrl: 'https://www.linkedin.com/in/mandar-kotnis-1331b9153',
    twitterUrl: '',
    facebookUrl: 'https://www.facebook.com/mandar.kotnis',
    instagramUrl: '',
  },
  {
    id: 4,
    name: 'Swapnil Shinde',
    imageUrl: 'https://avatars3.githubusercontent.com/u/37082605?s=460&v=4',
    githubUrl: 'https://github.com/Swap76',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: '',
    instagramUrl: 'https://www.instagram.com/swapnilsh007',
  },
  {
    id: 5,
    name: 'Shambhavi Sudarsan',
    imageUrl: 'https://avatars3.githubusercontent.com/u/43706184?s=460&v=4',
    githubUrl: 'https://github.com/ShambhaviSudarsan',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: 'https://www.facebook.com/shambhavi.sudarsan',
    instagramUrl: 'https://www.instagram.com/_shambhaviiiii',
  },
  {
    id: 6,
    name: 'Ashok Choudhary',
    imageUrl: 'https://media.licdn.com/dms/image/C5103AQFgxAdXbRRggg/profile-displayphoto-shrink_800_800/0?e=1567641600&v=beta&t=f8GTj93cSDS7g8Y7dTs9O0mieFwz3AjM1AN7p84Ohd8',
    githubUrl: 'https://github.com/ac030540',
    linkdinUrl: 'https://www.linkedin.com/in/ashok-choudhary-153a09150/',
    twitterUrl: '',
    facebookUrl: '',
  },
  {
    id: 7,
    name: 'Rahul Sawantdesai',
    imageUrl: 'https://avatars2.githubusercontent.com/u/37082780?s=460&v=4',
    githubUrl: 'https://github.com/rsd511',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: '',
    instagramUrl: '',
  },
  {
    id: 8,
    name: 'Ninad Chavan',
    imageUrl: 'https://avatars3.githubusercontent.com/u/42689621?s=460&v=4',
    githubUrl: 'https://github.com/ninadchavan',
    linkdinUrl: '',
    twitterUrl: 'https://twitter.com/@ninadchavan32',
    facebookUrl: 'https://facebook.com/ninadchavan',
    instagramUrl: 'https://instagram.com/ninadc32',
  },
  {
    id: 9,
    name: 'Harsh Agrawal',
    imageUrl: 'https://avatars3.githubusercontent.com/u/41856142?s=460&v=4',
    githubUrl: 'https://github.com/sneaky-beaver',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: 'https://www.facebook.com/profile.php?id=100004053384028',
    instagramUrl: 'https://www.instagram.com/sneaky___beaver',
  },
  {
    id: 10,
    name: 'Cibin Chandrashekhar',
    imageUrl: 'https://avatars2.githubusercontent.com/u/41542051?s=460&v=4',
    githubUrl: 'https://github.com/ShadowCBN',
    linkdinUrl: 'https://linkedin.com/in/prabhu-omkar',
    twitterUrl: 'https://twitter.com/@op_prabhuomkar',
    facebookUrl: 'https://www.facebook.com/cibin.chandrasekhar',
    instagramUrl: 'https://www.instagram.com/cbn.coooooool',
  },
  {
    id: 11,
    name: 'Mithil Poojary',
    imageUrl: 'https://avatars2.githubusercontent.com/u/41439841?s=460&v=4',
    githubUrl: 'https://github.com/mithil467',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: '',
    instagramUrl: '',
  },
  {
    id: 12,
    name: 'Barath Nadar',
    imageUrl: 'https://avatars0.githubusercontent.com/u/42098783?s=460&v=4',
    githubUrl: 'https://github.com/barath121',
    linkdinUrl: '',
    twitterUrl: 'https://mobile.twitter.com/BarathNadar',
    facebookUrl: 'https://www.facebook.com/barathsnadar',
    instagramUrl: 'https://www.instagram.com/nadarbarath/',
  },
];

export default developers;
