const developers = [
  {
    id: 1,
    name: 'Omkar Prabhu',
    imageUrl: 'https://avatars2.githubusercontent.com/u/31627958?s=460&v=4',
    githubUrl: 'https://github.com/prabhuomkar',
    linkdinUrl: 'https://linkedin.com/in/prabhu-omkar',
    twitterUrl: 'https://twitter.com/@op_prabhuomkar',
    facebookUrl: 'https://fb.com/op1111',
    instagramUrl: 'https://instagram.com/prabhu.omkar',
  },
  {
    id: 2,
    name: 'Siddharth Poduval',
    imageUrl: 'https://avatars1.githubusercontent.com/u/23222821?s=460&v=4',
    githubUrl: 'https://github.com/sudocoder98',
    linkdinUrl: 'https://www.linkedin.com/in/siddharth-poduval',
    twitterUrl: '',
    facebookUrl: 'https://fb.com/sid.poduval',
    instagramUrl: 'https://www.instagram.com/sid12598',
  },
  {
    id: 3,
    name: 'Swapnil Shinde',
    imageUrl: 'https://avatars3.githubusercontent.com/u/37082605?s=460&v=4',
    githubUrl: 'https://github.com/Swap76',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: '',
    instagramUrl: 'https://www.instagram.com/swapnilsh007',
  },
  {
    id: 4,
    name: 'Rahul Sawantdesai',
    imageUrl: 'https://avatars2.githubusercontent.com/u/37082780?s=460&v=4',
    githubUrl: 'https://github.com/rsd511',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: '',
    instagramUrl: '',
  },
  {
    id: 5,
    name: 'Ninad Chavan',
    imageUrl: 'https://avatars3.githubusercontent.com/u/42689621?s=460&v=4',
    githubUrl: 'https://github.com/ninadchavan',
    linkdinUrl: '',
    twitterUrl: 'https://twitter.com/@ninadchavan32',
    facebookUrl: 'https://facebook.com/ninadchavan',
    instagramUrl: 'https://instagram.com/ninadc32',
  },

  {
    id: 6,
    name: 'Shambhavi Sudarsan',
    imageUrl: 'https://avatars3.githubusercontent.com/u/43706184?s=460&v=4',
    githubUrl: 'https://github.com/ShambhaviSudarsan',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: 'https://www.facebook.com/shambhavi.sudarsan',
    instagramUrl: 'https://www.instagram.com/_shambhaviiiii',
  },
  {
    id: 7,
    name: 'Harsh Agrawal',
    imageUrl: 'https://avatars3.githubusercontent.com/u/41856142?s=460&v=4',
    githubUrl: 'https://github.com/sneaky-beaver',
    linkdinUrl: '',
    twitterUrl: '',
    facebookUrl: 'https://www.facebook.com/profile.php?id=100004053384028',
    instagramUrl: 'https://www.instagram.com/sneaky___beaver',
  },
  {
    id: 8,
    name: 'Cibin Chandrashekhar',
    imageUrl: 'https://avatars2.githubusercontent.com/u/41542051?s=460&v=4',
    githubUrl: 'https://github.com/ShadowCBN',
    linkdinUrl: 'https://linkedin.com/in/prabhu-omkar',
    twitterUrl: 'https://twitter.com/@op_prabhuomkar',
    facebookUrl: 'https://www.facebook.com/cibin.chandrasekhar',
    instagramUrl: 'https://www.instagram.com/cbn.coooooool',
  },
  {
    id: 9,
    name: 'Mandar Kotnis',
    imageUrl: 'https://avatars2.githubusercontent.com/u/27295746?s=460&v=4',
    githubUrl: 'https://github.com/Mandar-Kotnis',
    linkdinUrl: 'https://www.linkedin.com/in/mandar-kotnis-1331b9153',
    twitterUrl: '',
    facebookUrl: 'https://www.facebook.com/mandar.kotnis',
    instagramUrl: '',
  },
];

export default developers;
